server:
  port: 8081
spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
      enabled: true

