spring:
  application:
    name: server
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: iZ8vbdwu37doekt78hn1goZ
  client:
    service-url:
      defaultZone: http://8.142.84.98:8762/eureka/

---
spring:
  profiles: peer2
server:
  port: 8762

eureka:
  instance:
    hostname: iZ8vbgpdral5u703fjclzlZ
  client:
    service-url:
      defaultZone: http://39.103.180.84:8761/eureka/


