server:
  port: 9005
spring:
  application:
    name: config_server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/moo611/resource_center.git
          username: moo611
          password: 123456
          clone-on-start: true #开启启动时直接从git获取配置

